apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-cloud-config
data:
  # Kafka Configuration
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092" # The internal Kubernetes service name for Kafka
  RAW_DATA_TOPIC: "raw-data"
  H_PRIORITY_TOPIC: "H-priority-topic"
  M_PRIORITY_TOPIC: "M-priority-topic"
  L_PRIORITY_TOPIC: "L-priority-topic"
  DEFAULT_STREAM_TOPIC: "default-stream-topic"

  # InfluxDB Configuration
  INFLUXDB_URL: "http://influxdb-service:8086"
  INFLUXDB_ORG: "moby.lab"
  INFLUXDB_BUCKET: "edge-cloud-bucket"
  INFLUXB_TOKEN: "kpat_RvYpFT2Xuea3vWAAqaWmMnJ3vFjEyjYEoMvIarV3l3Ywrdy6Q" # Ensure this token has write permissions to the bucket

  # Orchestrator Configuration
  ORCHESTRATOR_URL: "http://orchestrator-service:80/api/v1" # Port 80 is the service port for the Orchestrator
  KONG_API_GATEWAY_URL: "http://kong-proxy/ingest" # The internal URL for producers to use
