apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-advance.fullname" . }}-configmap
data:
  index.html: |
    {{- .Values.pageContent.indexPage | nindent 4 }}
    <ul>
    {{- range .Values.extraPages }}
    {{- if .enabled }}
      <li><a href="/{{ .name }}.html">{{ .name | title }}</a></li>
    {{- end }}
    {{- end }}
    </ul>

  # This section builds the OTHER html files (about.html, contact.html)
  {{- range .Values.extraPages }}
  {{- if .enabled }}
  {{ .name }}.html: |
    {{- .content | nindent 4 }}
  {{- end }}
  {{- end }}
