apiVersion: v1
kind: Service
metadata:
  name: scheduler-service
spec:
  type: ClusterIP
  selector:
    app: scheduler
  ports:
    - protocol: TCP
      # This service will be available at http://scheduler-service:5001 inside the cluster
      port: 5001
      targetPort: 5001