apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  type: ClusterIP
  selector:
    app: orchestrator # This selector finds the pods managed by the Deployment above
  ports:
    - protocol: TCP
      port: 80 # The port the service will be available on within the cluster
      targetPort: 5000 # The port the container is listening on