controller:
  ingressController:
    image:
      tag: "3.4"
    env:
      feature_gates: "FillIDs=true"
      # KONG_ADMIN_URL: http://kong-gateway-kong-manager.kong.svc:8001
      # How do I authenticate to it?
      # KONG_ADMIN_TOKEN: "kpat_RvYpFT2Xuea3vWAAqaWmMnJ3vFjEyjYEoMvIarV3l3Ywrdy6Q"
    konnect:
      license:
        enabled: true
      enabled: true
      controlPlaneID: "501808aa-3d1c-4b1e-9a3c-839bed40290b"
      tlsClientCertSecretName: konnect-client-tls
      apiHostname: "us.kic.api.konghq.com"

gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.10"
  # admin:
  #   enabled: true
  #   type: ClusterIP
  #   service:
  #     name: kong-gateway-admin
  #     ports:
  #       http: 8001
  #       tls: 8444
  #   http:
  #     enabled: true
  #   tls:
  #     enabled: false
  #   ingress:
  #     enabled: true
  #     ingressClassName: kong
  #     hostname: 34.118.226.76.nip.io

  env:
    # KONG_ADMIN_TOKEN: "kpat_RvYpFT2Xuea3vWAAqaWmMnJ3vFjEyjYEoMvIarV3l3Ywrdy6Q"
    konnect_mode: "on"
    vitals: "off"
    cluster_mtls: pki
    cluster_telemetry_endpoint: "5467b0eecd.us.tp0.konghq.com:443"
    cluster_telemetry_server_name: "5467b0eecd.us.tp0.konghq.com"
    cluster_server_name: "edge-cloud-kong"
    cluster_cert: /etc/secrets/konnect-client-tls/tls.crt
    cluster_cert_key: /etc/secrets/konnect-client-tls/tls.key
    lua_ssl_trusted_certificate: system
    nginx_worker_processes: "1"
    upstream_keepalive_max_requests: "100000"
    nginx_http_keepalive_requests: "100000"
    proxy_access_log: "off"
    dns_stale_ttl: "3600"
    # enforce_rbac: "on"
    # admin_gui_auth: basic-auth
    # admin_gui_session_conf: '{"secret":"kong", "cookie_lifetime":300000, "cookie_renew":200000, "cookie_name":"kong_cookie", "cookie_secure":false, "cookie_samesite": "off"}'
    
  resources:
    requests:
      cpu: 1
      memory: "2Gi"
  secretVolumes:
    - konnect-client-tls
  manager:
    enabled: true
    type: ClusterIP